version: "3.7"
services:
  postgres-db:
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes: 
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    driver: local
