name: build
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@5e716dcfd653738c2d1db099bfba194a84158be4 # v2.3.0

      - name: Build and export to Docker client
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
        with:
          context: .
          file: Dockerfile
          load: true
          tags: |
            user/app:latest

      - name: Inspect image
        run: |
          docker image inspect user/app:latest
