name: golangci-lint
on:
  push
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v3.5
        with:
          go-version: 1.19
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # 3.3.1
        with:
          version: v1.50
